config/routes.rb
Myapp::Application.routes.draw do
  resources :samples
  root :to => redirect('/samples')
  
  match 'auth/:provider/callback' => 'session#create',:as => 'login'
  match 'logout' => 'sessions#destroy'

end

app/models/sample.rb
class Sample < ActiveRecord::Base
  attr_accessible :creator, :description, :location, :name, :variety, :visibility
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_protected :uid, :provider, :name
  attr_accessible :name, :provider, :uid
  def self.create_with_omniauth(auth)
    User.create!(
      :provider => auth["provider"],
      :uid => auth["uid"],
      :name => auth["info"]["name"])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @samples }
    end
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
    @sample = Sample.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/new
  # GET /samples/new.json
  def new
    @sample = Sample.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/1/edit
  def edit
    @sample = Sample.find(params[:id])
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(params[:sample])

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render json: @sample, status: :created, location: @sample }
      else
        format.html { render action: "new" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /samples/1
  # PUT /samples/1.json
  def update
    @sample = Sample.find(params[:id])

    respond_to do |format|
      if @sample.update_attributes(params[:sample])
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy

    respond_to do |format|
      format.html { redirect_to samples_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head   
    %title SamplR!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body{:style => "padding:40px"}
    %div{:class => "navbar navbar-inverse navbar-fixed-top"}
      %div{:class => "navbar-inner"}
        %div{:class => "container"}
          %a{:class =>"brand", :href => "#"}Igor
          %ul{:class => "nav"}
            %li.active
              %a{:href => "#"}Feed
            %li
              %a{:href => "#"}Your samples
            %li
              %a{:href => "#"}About
          %ul{:class => "nav pull-right"}
            %li
              %a{:hred => "#"}Login
      #main
        - if flash[:notice]
          #notice.message= flash[:notice]
        - elsif flash[:warning]
          #warning.message= flash[:warning]
        = yield

app/views/samples/_form.html.haml
%div.row
  %div.span2
  %div.span8
    = twitter_bootstrap_form_for @sample do |sample|
      - if @sample.errors.any?
        #error_explanation
          %h2= "#{pluralize(@sample.errors.count, "error")} prohibited this sample from being saved:"
          %ul
            - @sample.errors.full_messages.each do |msg|
              %li= msg
                  
              
      = sample.inputs 'New Sample', :class => 'new' do
        = sample.text_field :name, 'Sample Name', :class => 'input-block-level', :placeholder => 'GFP-IgG chimera'
        = sample.select :variety, 'Type of sample', {:Chemical => 'Chemical', :Biological => "Biological"}, :class => 'small'
        = sample.text_area :description, 'What is the sample?', :rows => 3
        = sample.text_field :location, 'Where is it?', :class => 'input-block-level', :placeholder => 'Fridge'
        = sample.text_field :creator, 'Who made the sample?', :class => 'input-block-level', :placeholder => 'Jane Doe'

        %label.radio
          %input{:type=>'radio', :name => :visibility, :id => 'visibility1', :value => :public, :checked => true}
            Make this sample publically visible
        %label.radio
          %input{:type=>'radio', :name => :visibility, :id => 'visibility2', :value => :private}
            Make this sample private and visible to you only
        
                      
          
        = sample.actions do
          = sample.submit 'Save', :class => 'btn btn-success'
          = button_tag 'Cancel', :type => 'reset', :class => 'btn btn-danger'
        
      
          
  %div.span2    
    

    

app/views/samples/edit.html.haml
%h1 Editing sample

= render 'form'

= link_to 'Show', @sample
\|
= link_to 'Back', samples_path

app/views/samples/feed.html.haml
%h1 Feed
%div.row
  %div.span6
    %table{:class => "table table-bordered"}
      %tr
        %th Name
        %th Type
        %th Description
        %th Location
        %th Creator
        %th
        %th
        %th
    
      - @samples.each do |sample|
        %tr
          %td= sample.name
          %td= sample.variety
          %td= sample.description
          %td= sample.location
          %td= sample.creator
          %td= link_to 'Show', sample
          %td= link_to 'Edit', edit_sample_path(sample)
          %td= link_to 'Destroy', sample, :method => :delete, :data => { :confirm => 'Are you sure?' }
  %div.span6
  This is a span 6	
          
    
    %br
= link_to 'New Sample', new_sample_path

app/views/samples/index.html.haml
%div.row
  %div.span1
  %div.span10
    %h1 Listing samples
    %table{:class => "table table-bordered table-striped table-hover"}
      %tr
        %th Name
        %th Type
        %th Description
        %th Location
        %th Creator
        %th
        %th
        %th
    
      - @samples.each do |sample|
        %tr
          %td= sample.name
          %td= sample.variety
          %td= sample.description
          %td= sample.location
          %td= sample.creator
          %td= link_to 'Show', sample
          %td= link_to 'Edit', edit_sample_path(sample)
          %td= link_to 'Destroy', sample, :method => :delete, :data => { :confirm => 'Are you sure?' }
    = link_to 'New Sample', new_sample_path, :class => 'btn btn-primary pull-right'
  %div.span1

app/views/samples/new.html.haml
%h1 New sample

= render 'form'

= link_to 'Back', samples_path

app/views/samples/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @sample.name
%p
  %b Variety:
  = @sample.variety
%p
  %b Description:
  = @sample.description
%p
  %b Location:
  = @sample.location
%p
  %b Creator:
  = @sample.creator

= link_to 'Edit', edit_sample_path(@sample)
\|
= link_to 'Back', samples_path